name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - develop
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
        jdkFile: 'jdk'

    - name: Build Spring Boot Application
      run: mvn clean package

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          SPRING_PROFILES_ACTIVE="prod"
        elif [[ ${{ github.ref }} == 'refs/heads/develop' ]]; then
          SPRING_PROFILES_ACTIVE="dev"
        elif [[ ${{ github.ref }} == 'refs/heads/feature/*' ]]; then
          SPRING_PROFILES_ACTIVE="dev"
        else
          SPRING_PROFILES_ACTIVE="default"
        fi
        echo $SPRING_PROFILES_ACTIVE
        echo docker build --build-arg SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE -t ${{ secrets.DOCKERHUB_USERNAME }}/userblog:${{ github.run_number }} .
        docker build --build-arg SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE -t ${{ secrets.DOCKERHUB_USERNAME }}/userblog:${{ github.run_number }} .

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/userblog:${{ github.run_number }}

