name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - develop
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
        jdkFile: 'jdk'

    - name: Build Spring Boot Application
      run: mvn clean package

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/your-app:${{ github.sha }}
        build-args: |
          SPRING_PROFILES_ACTIVE=$(get_profile ${{ github.ref }})

#    - name: Build Docker image
#      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/userblog:${{ github.run_number }} .
#
#    - name: Push Docker image to Docker Hub
#      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/userblog:${{ github.run_number }}

functions:
  get_profile: |
    if [[ $1 == 'refs/heads/main' ]]; then
      echo "prod"
    elif [[ $1 == 'refs/heads/develop' ]]; then
      echo "dev"
    elif [[ $1 == refs/heads/feature/* ]]; then
      echo "dev"
    else
      echo "default"
    fi